### ISSUE TITLE
Directory tree

### ISSUE THREAD

**Issue by monacofj** [courselab/soii21-carlos-melara#1]
Your directory tree should be

```
soii21-carlos-melara
   .gitignore
   AUTHORS                    <--- Edit this
   COPYING 
   README
   README.md                  <--- Edit this
   mbr
        your_files_for_mbr
   tyos
       your_files_for_tyos
   hw
       your_files_for_hw
```

Would you fix this? It would help me a lot.

**Comment by charles2910** [comment]
@monacofj o que deve ser editado em `README.md`? Já alterei o `AUTHORS`

**Comment by monacofj** [comment]
A ideia era que o README.md que veio é do enunciado, e seria interessante que fosse o README agora do seu projeto. Mas isso não é crítico... Fechando a issue..
